// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WxAuthRq struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxAuthRq) Reset()         { *m = WxAuthRq{} }
func (m *WxAuthRq) String() string { return proto.CompactTextString(m) }
func (*WxAuthRq) ProtoMessage()    {}
func (*WxAuthRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_e53190bbea6834a7, []int{0}
}
func (m *WxAuthRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxAuthRq.Unmarshal(m, b)
}
func (m *WxAuthRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxAuthRq.Marshal(b, m, deterministic)
}
func (dst *WxAuthRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxAuthRq.Merge(dst, src)
}
func (m *WxAuthRq) XXX_Size() int {
	return xxx_messageInfo_WxAuthRq.Size(m)
}
func (m *WxAuthRq) XXX_DiscardUnknown() {
	xxx_messageInfo_WxAuthRq.DiscardUnknown(m)
}

var xxx_messageInfo_WxAuthRq proto.InternalMessageInfo

func (m *WxAuthRq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type WxAuthRp struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Expire               int32    `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WxAuthRp) Reset()         { *m = WxAuthRp{} }
func (m *WxAuthRp) String() string { return proto.CompactTextString(m) }
func (*WxAuthRp) ProtoMessage()    {}
func (*WxAuthRp) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_e53190bbea6834a7, []int{1}
}
func (m *WxAuthRp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WxAuthRp.Unmarshal(m, b)
}
func (m *WxAuthRp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WxAuthRp.Marshal(b, m, deterministic)
}
func (dst *WxAuthRp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WxAuthRp.Merge(dst, src)
}
func (m *WxAuthRp) XXX_Size() int {
	return xxx_messageInfo_WxAuthRp.Size(m)
}
func (m *WxAuthRp) XXX_DiscardUnknown() {
	xxx_messageInfo_WxAuthRp.DiscardUnknown(m)
}

var xxx_messageInfo_WxAuthRp proto.InternalMessageInfo

func (m *WxAuthRp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *WxAuthRp) GetExpire() int32 {
	if m != nil {
		return m.Expire
	}
	return 0
}

type EditInfoRq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserIcon             string   `protobuf:"bytes,3,opt,name=user_icon,json=userIcon,proto3" json:"user_icon,omitempty"`
	UserCoin             float64  `protobuf:"fixed64,4,opt,name=user_coin,json=userCoin,proto3" json:"user_coin,omitempty"`
	UserBalance          float64  `protobuf:"fixed64,5,opt,name=user_balance,json=userBalance,proto3" json:"user_balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditInfoRq) Reset()         { *m = EditInfoRq{} }
func (m *EditInfoRq) String() string { return proto.CompactTextString(m) }
func (*EditInfoRq) ProtoMessage()    {}
func (*EditInfoRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_e53190bbea6834a7, []int{2}
}
func (m *EditInfoRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditInfoRq.Unmarshal(m, b)
}
func (m *EditInfoRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditInfoRq.Marshal(b, m, deterministic)
}
func (dst *EditInfoRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditInfoRq.Merge(dst, src)
}
func (m *EditInfoRq) XXX_Size() int {
	return xxx_messageInfo_EditInfoRq.Size(m)
}
func (m *EditInfoRq) XXX_DiscardUnknown() {
	xxx_messageInfo_EditInfoRq.DiscardUnknown(m)
}

var xxx_messageInfo_EditInfoRq proto.InternalMessageInfo

func (m *EditInfoRq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *EditInfoRq) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *EditInfoRq) GetUserIcon() string {
	if m != nil {
		return m.UserIcon
	}
	return ""
}

func (m *EditInfoRq) GetUserCoin() float64 {
	if m != nil {
		return m.UserCoin
	}
	return 0
}

func (m *EditInfoRq) GetUserBalance() float64 {
	if m != nil {
		return m.UserBalance
	}
	return 0
}

type EditInfoRp struct {
	Rp                   *EditInfoRq `protobuf:"bytes,1,opt,name=rp,proto3" json:"rp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EditInfoRp) Reset()         { *m = EditInfoRp{} }
func (m *EditInfoRp) String() string { return proto.CompactTextString(m) }
func (*EditInfoRp) ProtoMessage()    {}
func (*EditInfoRp) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_e53190bbea6834a7, []int{3}
}
func (m *EditInfoRp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditInfoRp.Unmarshal(m, b)
}
func (m *EditInfoRp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditInfoRp.Marshal(b, m, deterministic)
}
func (dst *EditInfoRp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditInfoRp.Merge(dst, src)
}
func (m *EditInfoRp) XXX_Size() int {
	return xxx_messageInfo_EditInfoRp.Size(m)
}
func (m *EditInfoRp) XXX_DiscardUnknown() {
	xxx_messageInfo_EditInfoRp.DiscardUnknown(m)
}

var xxx_messageInfo_EditInfoRp proto.InternalMessageInfo

func (m *EditInfoRp) GetRp() *EditInfoRq {
	if m != nil {
		return m.Rp
	}
	return nil
}

type GetInfoRq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInfoRq) Reset()         { *m = GetInfoRq{} }
func (m *GetInfoRq) String() string { return proto.CompactTextString(m) }
func (*GetInfoRq) ProtoMessage()    {}
func (*GetInfoRq) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_e53190bbea6834a7, []int{4}
}
func (m *GetInfoRq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRq.Unmarshal(m, b)
}
func (m *GetInfoRq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRq.Marshal(b, m, deterministic)
}
func (dst *GetInfoRq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRq.Merge(dst, src)
}
func (m *GetInfoRq) XXX_Size() int {
	return xxx_messageInfo_GetInfoRq.Size(m)
}
func (m *GetInfoRq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRq.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRq proto.InternalMessageInfo

func (m *GetInfoRq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetInfoRp struct {
	Info                 *EditInfoRq `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetInfoRp) Reset()         { *m = GetInfoRp{} }
func (m *GetInfoRp) String() string { return proto.CompactTextString(m) }
func (*GetInfoRp) ProtoMessage()    {}
func (*GetInfoRp) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_e53190bbea6834a7, []int{5}
}
func (m *GetInfoRp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInfoRp.Unmarshal(m, b)
}
func (m *GetInfoRp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInfoRp.Marshal(b, m, deterministic)
}
func (dst *GetInfoRp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInfoRp.Merge(dst, src)
}
func (m *GetInfoRp) XXX_Size() int {
	return xxx_messageInfo_GetInfoRp.Size(m)
}
func (m *GetInfoRp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInfoRp.DiscardUnknown(m)
}

var xxx_messageInfo_GetInfoRp proto.InternalMessageInfo

func (m *GetInfoRp) GetInfo() *EditInfoRq {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*WxAuthRq)(nil), "user.WxAuthRq")
	proto.RegisterType((*WxAuthRp)(nil), "user.WxAuthRp")
	proto.RegisterType((*EditInfoRq)(nil), "user.EditInfoRq")
	proto.RegisterType((*EditInfoRp)(nil), "user.EditInfoRp")
	proto.RegisterType((*GetInfoRq)(nil), "user.GetInfoRq")
	proto.RegisterType((*GetInfoRp)(nil), "user.GetInfoRp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserServiceClient interface {
	// 微信登录
	WxAuth(ctx context.Context, in *WxAuthRq, opts ...client.CallOption) (*WxAuthRp, error)
	// 更新用户信息
	EditInfo(ctx context.Context, in *EditInfoRq, opts ...client.CallOption) (*EditInfoRp, error)
	// 获取用户信息
	GetInfo(ctx context.Context, in *GetInfoRq, opts ...client.CallOption) (*GetInfoRp, error)
}

type userServiceClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceClient(serviceName string, c client.Client) UserServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "user"
	}
	return &userServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceClient) WxAuth(ctx context.Context, in *WxAuthRq, opts ...client.CallOption) (*WxAuthRp, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.WxAuth", in)
	out := new(WxAuthRp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) EditInfo(ctx context.Context, in *EditInfoRq, opts ...client.CallOption) (*EditInfoRp, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.EditInfo", in)
	out := new(EditInfoRp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetInfo(ctx context.Context, in *GetInfoRq, opts ...client.CallOption) (*GetInfoRp, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.GetInfo", in)
	out := new(GetInfoRp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	// 微信登录
	WxAuth(context.Context, *WxAuthRq, *WxAuthRp) error
	// 更新用户信息
	EditInfo(context.Context, *EditInfoRq, *EditInfoRp) error
	// 获取用户信息
	GetInfo(context.Context, *GetInfoRq, *GetInfoRp) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserService{hdlr}, opts...))
}

type UserService struct {
	UserServiceHandler
}

func (h *UserService) WxAuth(ctx context.Context, in *WxAuthRq, out *WxAuthRp) error {
	return h.UserServiceHandler.WxAuth(ctx, in, out)
}

func (h *UserService) EditInfo(ctx context.Context, in *EditInfoRq, out *EditInfoRp) error {
	return h.UserServiceHandler.EditInfo(ctx, in, out)
}

func (h *UserService) GetInfo(ctx context.Context, in *GetInfoRq, out *GetInfoRp) error {
	return h.UserServiceHandler.GetInfo(ctx, in, out)
}

func init() { proto.RegisterFile("proto/user.proto", fileDescriptor_user_e53190bbea6834a7) }

var fileDescriptor_user_e53190bbea6834a7 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x41, 0x4f, 0x3a, 0x31,
	0x10, 0xc5, 0xe9, 0xb2, 0xf0, 0x67, 0x87, 0x7f, 0x90, 0x4c, 0x8c, 0xd9, 0x40, 0x62, 0xd6, 0xc6,
	0x03, 0x31, 0x11, 0x15, 0x2f, 0x5e, 0xd5, 0x18, 0xc3, 0xc5, 0x43, 0x8d, 0xf1, 0x48, 0x96, 0x6e,
	0x89, 0x8d, 0xd0, 0x96, 0xb2, 0x18, 0x3e, 0x8b, 0x57, 0xbf, 0xa8, 0xd9, 0x16, 0x16, 0xc5, 0x70,
	0x9b, 0x79, 0xbf, 0x7d, 0x93, 0x37, 0xb3, 0x85, 0xb6, 0xb1, 0x3a, 0xd7, 0x17, 0xcb, 0x85, 0xb0,
	0x7d, 0x57, 0x62, 0x58, 0xd4, 0xf4, 0x18, 0x1a, 0xaf, 0xab, 0xdb, 0x65, 0xfe, 0xc6, 0xe6, 0x88,
	0x10, 0x72, 0x9d, 0x89, 0x98, 0x24, 0xa4, 0x17, 0x31, 0x57, 0xd3, 0x9b, 0x92, 0x1b, 0x3c, 0x84,
	0x5a, 0xae, 0xdf, 0x85, 0x5a, 0x7f, 0xe0, 0x1b, 0x3c, 0x82, 0xba, 0x58, 0x19, 0x69, 0x45, 0x1c,
	0x24, 0xa4, 0x57, 0x63, 0xeb, 0x8e, 0x7e, 0x11, 0x80, 0x87, 0x4c, 0xe6, 0x43, 0x35, 0xd1, 0x6c,
	0x8e, 0x2d, 0x08, 0x64, 0xe6, 0x9c, 0x55, 0x16, 0xc8, 0x0c, 0xbb, 0x10, 0x15, 0x01, 0x46, 0x2a,
	0x9d, 0x79, 0x67, 0xc4, 0x1a, 0x85, 0xf0, 0x94, 0xce, 0x44, 0x09, 0x25, 0xd7, 0x2a, 0xae, 0x6e,
	0xe1, 0x90, 0x6b, 0x55, 0x42, 0xae, 0xa5, 0x8a, 0xc3, 0x84, 0xf4, 0x88, 0x87, 0xf7, 0x5a, 0x2a,
	0x3c, 0x81, 0xff, 0x0e, 0x8e, 0xd3, 0x69, 0xaa, 0xb8, 0x88, 0x6b, 0x8e, 0x37, 0x0b, 0xed, 0xce,
	0x4b, 0xbe, 0x19, 0xcd, 0xf4, 0x58, 0x4e, 0x05, 0xed, 0xff, 0x08, 0x69, 0x30, 0x81, 0xc0, 0x1a,
	0x17, 0xb2, 0x39, 0x68, 0xf7, 0xdd, 0xb1, 0xb6, 0x2b, 0xb0, 0xc0, 0x1a, 0xda, 0x85, 0xe8, 0x51,
	0xec, 0xd9, 0x89, 0x5e, 0x6d, 0xa1, 0xc1, 0x53, 0x08, 0xa5, 0x9a, 0xe8, 0xbd, 0xd3, 0x1c, 0x1d,
	0x7c, 0x12, 0x68, 0xbe, 0x2c, 0x84, 0x7d, 0x16, 0xf6, 0x43, 0x72, 0x81, 0x67, 0x50, 0xf7, 0xf7,
	0xc6, 0x96, 0x77, 0x6c, 0xfe, 0x4e, 0xe7, 0x77, 0x6f, 0x68, 0x05, 0x2f, 0xa1, 0xb1, 0x99, 0x87,
	0x7f, 0xe6, 0x77, 0x76, 0x95, 0xc2, 0x71, 0x0e, 0xff, 0xd6, 0x01, 0xf1, 0xc0, 0xe3, 0x72, 0x99,
	0xce, 0x8e, 0x60, 0x68, 0x65, 0x5c, 0x77, 0x2f, 0xe5, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x0b,
	0x18, 0xf3, 0xae, 0x3d, 0x02, 0x00, 0x00,
}
